
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import MainLayout from "./home/layout"; 
import Header from "@/components/header/header";
import ReduxProvider from "@/store/ReduxProvider";

const roboto = Roboto({
  weight: ['400', '500','600',  '700'],
  style: ['normal', 'italic'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <ReduxProvider>
       <Header/>
       <MainLayout>
          {children}
        </MainLayout>
        </ReduxProvider> 
      </body>
    </html>
  );
}